# Generated by Django 4.2.7 on 2026-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('L', 'Low (L)'), ('M', 'Medium (M)'), ('H', 'High (H)')], default='M', max_length=1)),
                ('location', models.CharField(default='Plant A', max_length=100)),
                ('department', models.CharField(default='Production', max_length=100)),
                ('current_health_status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('critical', 'Critical'), ('offline', 'Offline')], default='healthy', max_length=20)),
                ('last_prediction_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['machine_id'],
            },
        ),
    ]
